# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_question.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_questionWidget(object):
    def setupUi(self, questionWidget):
        questionWidget.setObjectName("questionWidget")
        questionWidget.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(questionWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.contentWidget = QtWidgets.QFrame(self.centralwidget)
        self.contentWidget.setGeometry(QtCore.QRect(39, 20, 721, 521))
        self.contentWidget.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton {\n"
"    background-color: grey;\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QLineEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"}")
        self.contentWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentWidget.setObjectName("contentWidget")
        self.answer = QtWidgets.QLineEdit(self.contentWidget)
        self.answer.setGeometry(QtCore.QRect(130, 430, 321, 41))
        self.answer.setObjectName("answer")
        self.answer_label = QtWidgets.QLabel(self.contentWidget)
        self.answer_label.setGeometry(QtCore.QRect(30, 430, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.answer_label.setFont(font)
        self.answer_label.setObjectName("answer_label")
        self.nextButton = QtWidgets.QPushButton(self.contentWidget)
        self.nextButton.setGeometry(QtCore.QRect(500, 430, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.number_task = QtWidgets.QLabel(self.contentWidget)
        self.number_task.setGeometry(QtCore.QRect(10, 0, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.number_task.setFont(font)
        self.number_task.setAlignment(QtCore.Qt.AlignCenter)
        self.number_task.setObjectName("number_task")
        self.content = QtWidgets.QTextBrowser(self.contentWidget)
        self.content.setGeometry(QtCore.QRect(25, 51, 671, 351))
        self.content.setObjectName("content")
        self.warning = QtWidgets.QLabel(self.contentWidget)
        self.warning.setGeometry(QtCore.QRect(130, 480, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.warning.setFont(font)
        self.warning.setStyleSheet("QLabel {\n"
"    color: rgb(255, 35, 39);\n"
"}")
        self.warning.setObjectName("warning")
        self.exitButton = QtWidgets.QPushButton(self.contentWidget)
        self.exitButton.setGeometry(QtCore.QRect(660, 0, 61, 51))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    background-color: none;\n"
"}")
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/exit_to_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(64, 64))
        self.exitButton.setObjectName("exitButton")
        self.warning_2 = QtWidgets.QLabel(self.contentWidget)
        self.warning_2.setGeometry(QtCore.QRect(120, 400, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.warning_2.setFont(font)
        self.warning_2.setStyleSheet("QLabel {\n"
"    color: rgb(255, 35, 39);\n"
"}")
        self.warning_2.setText("")
        self.warning_2.setObjectName("warning_2")
        questionWidget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(questionWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        questionWidget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(questionWidget)
        self.statusbar.setObjectName("statusbar")
        questionWidget.setStatusBar(self.statusbar)

        self.retranslateUi(questionWidget)
        QtCore.QMetaObject.connectSlotsByName(questionWidget)

    def retranslateUi(self, questionWidget):
        _translate = QtCore.QCoreApplication.translate
        questionWidget.setWindowTitle(_translate("questionWidget", "Вопрос"))
        self.answer_label.setText(_translate("questionWidget", "Ответ:"))
        self.nextButton.setText(_translate("questionWidget", "Дальше"))
        self.number_task.setText(_translate("questionWidget", "Задание №"))
        self.warning.setText(_translate("questionWidget", "Учтите, что ответ вы должны записать без пробелов."))
