# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_MenuQuestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu_questions(object):
    def setupUi(self, Menu_questions):
        Menu_questions.setObjectName("Menu_questions")
        Menu_questions.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Menu_questions)
        self.centralwidget.setObjectName("centralwidget")
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(19, 9, 771, 541))
        self.content.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(174, 120, 255);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.compiler_table = QtWidgets.QTableWidget(self.content)
        self.compiler_table.setGeometry(QtCore.QRect(35, 51, 451, 451))
        self.compiler_table.setObjectName("compiler_table")
        self.compiler_table.setColumnCount(0)
        self.compiler_table.setRowCount(0)
        self.exitButton = QtWidgets.QPushButton(self.content)
        self.exitButton.setGeometry(QtCore.QRect(710, 0, 61, 51))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    background-color: none;\n"
"}")
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/exit_to_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(64, 64))
        self.exitButton.setObjectName("exitButton")
        self.make_up = QtWidgets.QFrame(self.content)
        self.make_up.setGeometry(QtCore.QRect(500, 69, 261, 411))
        self.make_up.setStyleSheet("QFrame {\n"
"    background-color: rgb(200, 198, 255);\n"
"}")
        self.make_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.make_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.make_up.setObjectName("make_up")
        self.beginButton = QtWidgets.QPushButton(self.make_up)
        self.beginButton.setGeometry(QtCore.QRect(30, 30, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.beginButton.setFont(font)
        self.beginButton.setStyleSheet("")
        self.beginButton.setObjectName("beginButton")
        self.clearButton = QtWidgets.QPushButton(self.make_up)
        self.clearButton.setGeometry(QtCore.QRect(0, 180, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"    color: black;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon1)
        self.clearButton.setObjectName("clearButton")
        self.allButton = QtWidgets.QPushButton(self.make_up)
        self.allButton.setGeometry(QtCore.QRect(0, 110, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.allButton.setFont(font)
        self.allButton.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"    color: black;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icon/all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.allButton.setIcon(icon2)
        self.allButton.setObjectName("allButton")
        Menu_questions.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu_questions)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Menu_questions.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu_questions)
        self.statusbar.setObjectName("statusbar")
        Menu_questions.setStatusBar(self.statusbar)

        self.retranslateUi(Menu_questions)
        QtCore.QMetaObject.connectSlotsByName(Menu_questions)

    def retranslateUi(self, Menu_questions):
        _translate = QtCore.QCoreApplication.translate
        Menu_questions.setWindowTitle(_translate("Menu_questions", "Menu Questions"))
        self.beginButton.setText(_translate("Menu_questions", "Составить вариант"))
        self.clearButton.setText(_translate("Menu_questions", "Убрать все"))
        self.allButton.setText(_translate("Menu_questions", "Выбрать все"))
