# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_loadingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.resize(595, 477)
        self.content = QtWidgets.QFrame(LoadingWindow)
        self.content.setGeometry(QtCore.QRect(10, 20, 571, 441))
        self.content.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(169, 111, 255);\n"
"}")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.progressBar = QtWidgets.QProgressBar(self.content)
        self.progressBar.setGeometry(QtCore.QRect(40, 380, 491, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(124, 113, 116);\n"
"    border-radius: 10px;\n"
"    color:white;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(224, 83, 0, 255), stop:1 rgba(171, 13, 212, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_rus = QtWidgets.QLabel(self.content)
        self.label_rus.setGeometry(QtCore.QRect(10, 170, 561, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_rus.setFont(font)
        self.label_rus.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.label_rus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rus.setObjectName("label_rus")
        self.image = QtWidgets.QLabel(self.content)
        self.image.setGeometry(QtCore.QRect(10, 20, 551, 141))
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")

        self.retranslateUi(LoadingWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "LoadingWindow"))
        self.label_rus.setText(_translate("LoadingWindow", "Русский язык"))
