# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonWidget = QtWidgets.QFrame(self.centralwidget)
        self.ButtonWidget.setGeometry(QtCore.QRect(9, 9, 780, 550))
        self.ButtonWidget.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 30px;\n"
"    background-color: grey;\n"
"    color: white\n"
"}")
        self.ButtonWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.ProfileWidget = QtWidgets.QFrame(self.ButtonWidget)
        self.ProfileWidget.setGeometry(QtCore.QRect(-1, -1, 390, 551))
        self.ProfileWidget.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(162, 0, 255, 255), stop:1 rgba(255, 0, 255, 255));\n"
"}\n"
"QLabel{\n"
"    background-color: none;\n"
"}\n"
"QTextEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ProfileWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProfileWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProfileWidget.setObjectName("ProfileWidget")
        self.title_profile = QtWidgets.QLabel(self.ProfileWidget)
        self.title_profile.setGeometry(QtCore.QRect(0, 0, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        self.title_profile.setFont(font)
        self.title_profile.setStyleSheet("QLabel {\n"
"    background-color: none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.title_profile.setAlignment(QtCore.Qt.AlignCenter)
        self.title_profile.setObjectName("title_profile")
        self.avatar = QtWidgets.QLabel(self.ProfileWidget)
        self.avatar.setGeometry(QtCore.QRect(10, 90, 151, 191))
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")
        self.name = QtWidgets.QLineEdit(self.ProfileWidget)
        self.name.setEnabled(False)
        self.name.setGeometry(QtCore.QRect(170, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"}")
        self.name.setObjectName("name")
        self.surname = QtWidgets.QLineEdit(self.ProfileWidget)
        self.surname.setEnabled(False)
        self.surname.setGeometry(QtCore.QRect(170, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.surname.setFont(font)
        self.surname.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"}")
        self.surname.setObjectName("surname")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.ProfileWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 380, 371, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quote_1_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_1_1.setObjectName("quote_1_1")
        self.verticalLayout.addWidget(self.quote_1_1)
        self.quote_1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_1_2.setObjectName("quote_1_2")
        self.verticalLayout.addWidget(self.quote_1_2)
        self.quote_2_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_2_1.setObjectName("quote_2_1")
        self.verticalLayout.addWidget(self.quote_2_1)
        self.quote_2_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_2_2.setObjectName("quote_2_2")
        self.verticalLayout.addWidget(self.quote_2_2)
        self.quote_3_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_3_1.setObjectName("quote_3_1")
        self.verticalLayout.addWidget(self.quote_3_1)
        self.quote_3_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quote_3_2.setObjectName("quote_3_2")
        self.verticalLayout.addWidget(self.quote_3_2)
        self.title_ege = QtWidgets.QLabel(self.ButtonWidget)
        self.title_ege.setGeometry(QtCore.QRect(396, 9, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setPointSize(30)
        self.title_ege.setFont(font)
        self.title_ege.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_ege.setAlignment(QtCore.Qt.AlignCenter)
        self.title_ege.setObjectName("title_ege")
        self.title_russia = QtWidgets.QLabel(self.ButtonWidget)
        self.title_russia.setGeometry(QtCore.QRect(390, 60, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setPointSize(30)
        self.title_russia.setFont(font)
        self.title_russia.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_russia.setAlignment(QtCore.Qt.AlignCenter)
        self.title_russia.setObjectName("title_russia")
        self.theoryButton = QtWidgets.QPushButton(self.ButtonWidget)
        self.theoryButton.setGeometry(QtCore.QRect(420, 150, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setPointSize(14)
        self.theoryButton.setFont(font)
        self.theoryButton.setObjectName("theoryButton")
        self.practiceButton = QtWidgets.QPushButton(self.ButtonWidget)
        self.practiceButton.setGeometry(QtCore.QRect(420, 240, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setPointSize(14)
        self.practiceButton.setFont(font)
        self.practiceButton.setObjectName("practiceButton")
        self.statisticButton = QtWidgets.QPushButton(self.ButtonWidget)
        self.statisticButton.setGeometry(QtCore.QRect(420, 330, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setPointSize(14)
        self.statisticButton.setFont(font)
        self.statisticButton.setObjectName("statisticButton")
        self.copyright = QtWidgets.QLabel(self.ButtonWidget)
        self.copyright.setGeometry(QtCore.QRect(680, 510, 91, 20))
        self.copyright.setObjectName("copyright")
        self.exitButton = QtWidgets.QPushButton(self.ButtonWidget)
        self.exitButton.setGeometry(QtCore.QRect(720, 0, 61, 51))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    background-color: none;\n"
"}")
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/exit_to_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(64, 64))
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_profile.setText(_translate("MainWindow", "Мой профиль"))
        self.name.setText(_translate("MainWindow", "ИМЯ"))
        self.surname.setText(_translate("MainWindow", "ФАМИЛИЯ"))
        self.quote_1_1.setText(_translate("MainWindow", "«Великие дела совершаются серией маленьких вещей, собранных "))
        self.quote_1_2.setText(_translate("MainWindow", "вместе». — Винсент Ван Гог."))
        self.quote_2_1.setText(_translate("MainWindow", "«Учитесь у вчерашнего дня, живите сегодняшним днем, надейтесь"))
        self.quote_2_2.setText(_translate("MainWindow", "на завтра». — Альберт Эйнштейн."))
        self.quote_3_1.setText(_translate("MainWindow", "«Учеба без желания портит память, и она не сохраняет ничего,"))
        self.quote_3_2.setText(_translate("MainWindow", " что принимает». — Леонардо да Винчи."))
        self.title_ege.setText(_translate("MainWindow", "Е Г Э"))
        self.title_russia.setText(_translate("MainWindow", "РУССКИЙ ЯЗЫК"))
        self.theoryButton.setText(_translate("MainWindow", "ТЕОРИЯ"))
        self.practiceButton.setText(_translate("MainWindow", "ПРАКТИКА"))
        self.statisticButton.setText(_translate("MainWindow", "СТАТИСТИКА"))
        self.copyright.setText(_translate("MainWindow", " © usato-polosato"))
