# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_diagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiagramWidget(object):
    def setupUi(self, DiagramWidget):
        DiagramWidget.setObjectName("DiagramWidget")
        DiagramWidget.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DiagramWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.contentWidget = QtWidgets.QFrame(self.centralwidget)
        self.contentWidget.setGeometry(QtCore.QRect(50, 30, 721, 521))
        self.contentWidget.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton {\n"
"    background-color: grey;\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QLineEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"}")
        self.contentWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentWidget.setObjectName("contentWidget")
        self.number_task = QtWidgets.QLabel(self.contentWidget)
        self.number_task.setGeometry(QtCore.QRect(10, 0, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.number_task.setFont(font)
        self.number_task.setAlignment(QtCore.Qt.AlignCenter)
        self.number_task.setObjectName("number_task")
        self.exitButton = QtWidgets.QPushButton(self.contentWidget)
        self.exitButton.setGeometry(QtCore.QRect(660, 0, 61, 51))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    background-color: none;\n"
"}")
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/exit_to_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(64, 64))
        self.exitButton.setObjectName("exitButton")
        self.diagram = QtWidgets.QGraphicsView(self.contentWidget)
        self.diagram.setGeometry(QtCore.QRect(100, 40, 500, 350))
        self.diagram.setObjectName("diagram")
        self.label_percent = QtWidgets.QLabel(self.contentWidget)
        self.label_percent.setGeometry(QtCore.QRect(10, 410, 711, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_percent.setFont(font)
        self.label_percent.setObjectName("label_percent")
        self.result = QtWidgets.QLabel(self.contentWidget)
        self.result.setGeometry(QtCore.QRect(466, 410, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.result.setFont(font)
        self.result.setStyleSheet("QLabel {\n"
"    color: rgb(42, 255, 56);\n"
"}")
        self.result.setText("")
        self.result.setObjectName("result")
        # DiagramWidget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DiagramWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        # DiagramWidget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DiagramWidget)
        self.statusbar.setObjectName("statusbar")
        # DiagramWidget.setStatusBar(self.statusbar)

        self.retranslateUi(DiagramWidget)
        QtCore.QMetaObject.connectSlotsByName(DiagramWidget)

    def retranslateUi(self, DiagramWidget):
        _translate = QtCore.QCoreApplication.translate
        DiagramWidget.setWindowTitle(_translate("DiagramWidget", "Статистика в диаграммах"))
        self.number_task.setText(_translate("DiagramWidget", "Задание №"))
        self.label_percent.setText(_translate("DiagramWidget", "Процент выполнения данного задания:"))
